### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by adamlwgriffiths** [adamlwgriffiths/amazon_scraper#10]
Let me know when you're happy with what you've commited.
We'll tag it and release it on PyPi.

Do you have a pypi account?
If so, let me know the username and I'll give you release permissions.

**Comment by hahnicity** [comment]
yeah I do. Username: grehm87

**Comment by adamlwgriffiths** [comment]
Done =)

Once you're done, let's set the version to either 0.2.0 or 1.0.0 in version.py, tag it with the version, and push it out.

**Comment by hahnicity** [comment]
done. I decided on version 0.2

**Comment by adamlwgriffiths** [comment]
Thanks for doing the release.
Sorry I haven't been able to provide code / releases. To say it's been hectic lately is an understatement.

Please know that your efforts are appreciated =)
