### ISSUE TITLE
reviews return only 10 results

### ISSUE THREAD

**Issue by amitbend** [adamlwgriffiths/amazon_scraper#13]
i tried the function:
rs = amzn.reviews(URL=p.reviews_url)

it return only <10 results.(unless i'm missing something)

**Comment by adamlwgriffiths** [comment]
Yep, what you'll need to do is iterate over `rs`.

The reviews object only really parses the one page, it has a 'next_page' property that you can then pass into the function you mentioned above to get the next page.

The reviews functions only return the results for the page being parsed, hence 10 results.

There is an `__iter__` function that lets you get the first page and then iterate over the reviews.
```
rs = amzn.reviews(URL=p.reviews_url)
# print the review ids on this reviews page
print(rs.ids)
# print ALL review ids from this page onwards
for r in rs:
    print(r.id)
```

I appreciate that this may not be intuitive.

**Comment by adamlwgriffiths** [comment]
I've added a small example to the README.

**Comment by amitbend** [comment]
Thank you!

**Comment by adamlwgriffiths** [comment]
Glad to have helped =)
