### ISSUE TITLE
extract_asin doesn't work with all Amazon's links

### ISSUE THREAD

**Issue by apapillon** [adamlwgriffiths/amazon_scraper#18]
On Amazon home page, the product link are different and ``extract_asin`` doesn't work.
I propose you to change ``_extract_asin_regexp`` by ``(/dp/|/gp/product/)(?P<asin>[^/]+)/``

~~~~ python
#_extract_asin_regexp = re.compile(r'/dp/(?P<asin>[^/]+)/')
_extract_asin_regexp = re.compile(r'(/dp/|/gp/product/)(?P<asin>[^/]+)/')
~~~~

Example of link : http://www.amazon.com/gp/product/B00GBHZDY4/

**Comment by adamlwgriffiths** [comment]
Thanks for raising the issue and fixing it =)
I've added you as a collaborator.
