### ISSUE TITLE
Only getting the last 10 reviews

### ISSUE THREAD

**Issue by Jonovono** [adamlwgriffiths/amazon_scraper#21]
I seem to be able to only get the last 10 reviews. Is this known?

**Comment by adamlwgriffiths** [comment]
#20

**Comment by adamlwgriffiths** [comment]
If that doesn't resolve your issue, then please provide more information or I cannot help you.

**Comment by Jonovono** [comment]
Sorry @adamlwgriffiths looks like I didn't have an up to date version. It's working great! Thanks a lot :)
