### ISSUE TITLE
Problem installing amazon_scraper

### ISSUE THREAD

**Issue by Sebiti** [adamlwgriffiths/amazon_scraper#22]
Either installing from command line using pip or through PyCharm, I get the following error message:

//
Collecting amazon-scraper
  Using cached amazon_scraper-0.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\...\AppData\Local\Temp\pycharm-packaging0.tmp\amazon-scraper\setup.py", line 4, in <module>
        del os.link
    AttributeError: link
//

By deleting this line I think it installs OK (I have tried it and used the scraper some time ago). 
The problem is when trying to install the scraper automatically using an IDE. I am running PyCharm on Windows 8.1, if this could indicate the source of the problem. Are any Linux users getting this error?
Any help would be appreciated.

**Comment by adamlwgriffiths** [comment]
It should be safe to delete, it seems its for an odd issue that I haven't personally encountered.
https://bugs.python.org/issue8876#msg208792

It's just removing the function `link` from the `os` module.
This should be present for both 2.7 and 3.2+.

I'll wrap it in a `try` block which should fix it.

**Comment by Sebiti** [comment]
Thank you.

**Comment by adamlwgriffiths** [comment]
Wrapped in a try and pushed to pypi as 0.3.3.
Please check if this resolves your issue.
If not, please re-open the issue.
