### ISSUE TITLE
How to get offer listings(all offer price by all merchants for single product)

### ISSUE THREAD

**Issue by ganganimaulik** [adamlwgriffiths/amazon_scraper#28]
example : http://www.amazon.com/gp/offer-listing/B00OBRE5UE/

**Comment by adamlwgriffiths** [comment]
I haven't written anything for scraping individual sellers - new or used.
It should be a matter of finding the url, if present, the passing that to another scraper to extract the data from the new page.

I don't have time to work on this. If you do, please feel free to make a pull request and I can provide some assistance.
