### ISSUE TITLE
Incorrect Syntax in init

### ISSUE THREAD

**Issue by rmeier11** [adamlwgriffiths/amazon_scraper#3]
Hi,

I get an error when installing and running in __init__.py in line 60.
It says: "incorrect syntax": _price_regexp = re.compile(ur'(?P<price>[$ú][\d,\.]+)', flags=re.I).
The arrow is on the last '.

Also in product.py line 50, reviews.py line 60.

**Comment by adamlwgriffiths** [comment]
What version of python are you using?

**Comment by rmeier11** [comment]
3.4.2

**Comment by adamlwgriffiths** [comment]
Bam, I don't use python 3 nor have i tested this code with it.
The fix should be simple, but I don't know what it is.
I'd say it doesn't like the unicode raw strings. `ur''`. Removing that would cause issues with python 2 though. Perhaps run 2to3 over the project.

**Comment by hahnicity** [comment]
@adamlwgriffiths are we interested in 3 compatibility? It should probably be pretty easy to do with unit tests

**Comment by adamlwgriffiths** [comment]
It would be good to support Python 3.
Personally, I don't use it. I also don't have the time to make such changes, unfortunately.
I think it's really limited to the `ur''` strings. Which I believe we need for that regexp.
Might be able to run 2to3 as part of setup.

**Comment by kashht** [comment]
Has there been any progress on 2-3 migration?

**Comment by adamlwgriffiths** [comment]
I haven't had any time to do any coding outside of work.
I think running python 2to3 would solve this.
Patches are welcome.

**Comment by adamlwgriffiths** [comment]
Python 3 should be supported as of 0.3.1
See this 265bfacf2430894829e1d47c61a9b4f690af3816 for changes
