### ISSUE TITLE
Get Product Price 

### ISSUE THREAD

**Issue by qasimahsan77** [adamlwgriffiths/amazon_scraper#30]
Sir can you please tell me how to get the Product price through your amazon_scraper API in Python. and also tell me how to get Seller Information.

**Comment by adamlwgriffiths** [comment]
amazon_scraper is layered on top of [amazon simple product api](https://pypi.python.org/pypi/python-amazon-simple-product-api/).

From their documentation:

```
>>> product.price_and_currency
(89.0, 'USD')
```

As mentioned in #28, I do not have any code to scrape sellers
