### ISSUE TITLE
Add ability to set amazon_base

### ISSUE THREAD

**Issue by n1try** [adamlwgriffiths/amazon_scraper#35]
Regardless of the `Region` parameter, product reviews are always tried to be fetched from `http://www.amazon.com/product-reviews/` due to the [amazon_base](https://github.com/adamlwgriffiths/amazon_scraper/blob/master/amazon_scraper/__init__.py#L36) constant. 
I'd suggest that this base url either is set dynamically, depending on the `Region` or can be specified as a paramter, without having to statically overwrite the variable.

**Comment by adamlwgriffiths** [comment]
You can manually assign the value of this variable and it will be used, which is the same as passing it as a parameter, except with less code.
The only thing it really needs is documenting.

**Comment by adamlwgriffiths** [comment]
Just to clairfy, if you want to add this feel free to do a PR.
