### ISSUE TITLE
AWS Accout

### ISSUE THREAD

**Issue by amysmiths** [adamlwgriffiths/amazon_scraper#40]
Do I need a AWS account for this to work?

**Comment by adamlwgriffiths** [comment]
https://pypi.python.org/pypi/python-amazon-simple-product-api/

> Before you get started, make sure you have:
> 
> Installed [Bottlenose](https://github.com/lionheart/bottlenose) (pip install bottlenose)
> Installed lxml (pip install lxml)
> Installed [dateutil](http://labix.org/python-dateutil) (pip install python-dateutil)
> An Amazon Product Advertising account
> An AWS account
