### ISSUE TITLE
Install requirement contains invalid library name

### ISSUE THREAD

**Issue by techcentaur** [adamlwgriffiths/amazon_scraper#42]
Installing requirements should have a library named bs4; beautifulsoup4 is not a valid library (python--v>3)

**Comment by adamlwgriffiths** [comment]
I don't think that's correct.

https://pypi.org/project/bs4/
> This is a dummy package managed by the developer of Beautiful Soup to prevent name squatting. The official name of PyPI’s Beautiful Soup Python package is beautifulsoup4. This package ensures that if you type pip install bs4 by mistake you will end up with Beautiful Soup.

**Comment by techcentaur** [comment]
I apologize for my lack of information, thanks for the clarification.
